#############################################################################
# Makefile for building: bin/data_plot
# Generated by qmake (2.01a) (Qt 4.5.1) on: Tue Jan 17 11:23:04 2012
# Project:  data_plot.pro
# Template: app
# Command: /home/doug/qtsdk-2009.02/qt/bin/qmake -spec ../../qtsdk-2009.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile data_plot.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2009.02/qt/mkspecs/linux-g++ -I. -I../../qtsdk-2009.02/qt/include/QtCore -I../../qtsdk-2009.02/qt/include/QtGui -I../../qtsdk-2009.02/qt/include -I../../src -I/usr/local/qwt-5.1.2/include -Imoc -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/local/lib/LabVIEW-2010/patchlib -Wl,-rpath,/home/doug/qtsdk-2009.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/doug/qtsdk-2009.02/qt/lib -L../../lib -lqwt -L/opt/fontconfig-2.4.2/lib -lnidaqmxbase /usr/local/lib/LabVIEW-2010/patchlib/libstdc++.so.6 -I/usr/local/qwt-5.1.2/lib -lQtGui -L/home/doug/qtsdk-2009.02/qt/lib -L/usr/X11R6/lib -pthread -lfreetype -lgobject-2.0 -lSM -lICE -pthread -pthread -lXrender -lfontconfig -lXext -lX11 -lQtCore -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/doug/qtsdk-2009.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = data_plot.cpp \
		main.cpp \
		hist_plot.cpp \
		histogram_item.cpp \
		para.cpp moc/moc_data_plot.cpp \
		moc/moc_hist_plot.cpp \
		moc/moc_main.cpp \
		moc/moc_para.cpp
OBJECTS       = obj/data_plot.o \
		obj/main.o \
		obj/hist_plot.o \
		obj/histogram_item.o \
		obj/para.o \
		obj/moc_data_plot.o \
		obj/moc_hist_plot.o \
		obj/moc_main.o \
		obj/moc_para.o
DIST          = ../../qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		examples.pri \
		../../qtsdk-2009.02/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		data_plot.pro
QMAKE_TARGET  = data_plot
DESTDIR       = bin/
TARGET        = bin/data_plot

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: data_plot.pro  ../../qtsdk-2009.02/qt/mkspecs/linux-g++/qmake.conf ../../qtsdk-2009.02/qt/mkspecs/common/g++.conf \
		../../qtsdk-2009.02/qt/mkspecs/common/unix.conf \
		../../qtsdk-2009.02/qt/mkspecs/common/linux.conf \
		../../qtsdk-2009.02/qt/mkspecs/qconfig.pri \
		../../qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/default_pre.prf \
		examples.pri \
		../../qtsdk-2009.02/qt/mkspecs/features/debug.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/qt.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/moc.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/resources.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/uic.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/lex.prf \
		../../qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf \
		/home/doug/qtsdk-2009.02/qt/lib/libQtGui.prl \
		/home/doug/qtsdk-2009.02/qt/lib/libQtCore.prl
	$(QMAKE) -spec ../../qtsdk-2009.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile data_plot.pro
../../qtsdk-2009.02/qt/mkspecs/common/g++.conf:
../../qtsdk-2009.02/qt/mkspecs/common/unix.conf:
../../qtsdk-2009.02/qt/mkspecs/common/linux.conf:
../../qtsdk-2009.02/qt/mkspecs/qconfig.pri:
../../qtsdk-2009.02/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2009.02/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2009.02/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2009.02/qt/mkspecs/features/default_pre.prf:
examples.pri:
../../qtsdk-2009.02/qt/mkspecs/features/debug.prf:
../../qtsdk-2009.02/qt/mkspecs/features/default_post.prf:
../../qtsdk-2009.02/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2009.02/qt/mkspecs/features/qt.prf:
../../qtsdk-2009.02/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2009.02/qt/mkspecs/features/moc.prf:
../../qtsdk-2009.02/qt/mkspecs/features/resources.prf:
../../qtsdk-2009.02/qt/mkspecs/features/uic.prf:
../../qtsdk-2009.02/qt/mkspecs/features/yacc.prf:
../../qtsdk-2009.02/qt/mkspecs/features/lex.prf:
../../qtsdk-2009.02/qt/mkspecs/features/include_source_dir.prf:
/home/doug/qtsdk-2009.02/qt/lib/libQtGui.prl:
/home/doug/qtsdk-2009.02/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../qtsdk-2009.02/qt/mkspecs/linux-g++ -unix CONFIG+=debug -o Makefile data_plot.pro

dist: 
	@$(CHK_DIR_EXISTS) obj/data_plot1.0.0 || $(MKDIR) obj/data_plot1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) obj/data_plot1.0.0/ && $(COPY_FILE) --parents data_plot.h hist_plot.h histogram_item.h main.h para.h obj/data_plot1.0.0/ && $(COPY_FILE) --parents data_plot.cpp main.cpp hist_plot.cpp histogram_item.cpp para.cpp obj/data_plot1.0.0/ && (cd `dirname obj/data_plot1.0.0` && $(TAR) data_plot1.0.0.tar data_plot1.0.0 && $(COMPRESS) data_plot1.0.0.tar) && $(MOVE) `dirname obj/data_plot1.0.0`/data_plot1.0.0.tar.gz . && $(DEL_FILE) -r obj/data_plot1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_data_plot.cpp moc/moc_hist_plot.cpp moc/moc_main.cpp moc/moc_para.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_data_plot.cpp moc/moc_hist_plot.cpp moc/moc_main.cpp moc/moc_para.cpp
moc/moc_data_plot.cpp: NIDAQmxBase.h \
		data_plot.h
	/home/doug/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) data_plot.h -o moc/moc_data_plot.cpp

moc/moc_hist_plot.cpp: histogram_item.h \
		hist_plot.h
	/home/doug/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) hist_plot.h -o moc/moc_hist_plot.cpp

moc/moc_main.cpp: para.h \
		main.h
	/home/doug/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) main.h -o moc/moc_main.cpp

moc/moc_para.cpp: para.h
	/home/doug/qtsdk-2009.02/qt/bin/moc $(DEFINES) $(INCPATH) para.h -o moc/moc_para.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

obj/data_plot.o: data_plot.cpp data_plot.h \
		NIDAQmxBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/data_plot.o data_plot.cpp

obj/main.o: main.cpp main.h \
		para.h \
		data_plot.h \
		NIDAQmxBase.h \
		hist_plot.h \
		histogram_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/hist_plot.o: hist_plot.cpp hist_plot.h \
		histogram_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/hist_plot.o hist_plot.cpp

obj/histogram_item.o: histogram_item.cpp histogram_item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/histogram_item.o histogram_item.cpp

obj/para.o: para.cpp para.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/para.o para.cpp

obj/moc_data_plot.o: moc/moc_data_plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_data_plot.o moc/moc_data_plot.cpp

obj/moc_hist_plot.o: moc/moc_hist_plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_hist_plot.o moc/moc_hist_plot.cpp

obj/moc_main.o: moc/moc_main.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_main.o moc/moc_main.cpp

obj/moc_para.o: moc/moc_para.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_para.o moc/moc_para.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

